# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ned/proprietarytoro/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/ned/proprietarytoro/proprietary/libsecril-client.so:obj/lib/libsecril-client.so

# All the blobs necessary for toro
PRODUCT_COPY_FILES += \
    vendor/ned/proprietarytoro/proprietary/fRom:system/bin/fRom \
    vendor/ned/proprietarytoro/proprietary/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/ned/proprietarytoro/proprietary/libsyncml_core.so:system/lib/libsyncml_core.so \
    vendor/ned/proprietarytoro/proprietary/libsyncml_port.so:system/lib/libsyncml_port.so \
    vendor/ned/proprietarytoro/proprietary/lib_gsd4t.so:system/lib/lib_gsd4t.so \
    vendor/ned/proprietarytoro/proprietary/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/ned/proprietarytoro/proprietary/sirfgps.conf:system/vendor/etc/sirfgps.conf \
    vendor/ned/proprietarytoro/proprietary/bcm4330.hcd:system/vendor/firmware/bcm4330.hcd \
    vendor/ned/proprietarytoro/proprietary/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/ned/proprietarytoro/proprietary/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/ned/proprietarytoro/proprietary/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/ned/proprietarytoro/proprietary/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/ned/proprietarytoro/proprietary/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/ned/proprietarytoro/proprietary/gps.omap4.so:system/vendor/lib/hw/gps.omap4.so \
    vendor/ned/proprietarytoro/proprietary/gralloc.omap4.so:system/vendor/lib/hw/gralloc.omap4.so \
    vendor/ned/proprietarytoro/proprietary/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/ned/proprietarytoro/proprietary/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/ned/proprietarytoro/proprietary/libims.so:system/vendor/lib/libims.so \
    vendor/ned/proprietarytoro/proprietary/libims_jni.so:system/vendor/lib/libims_jni.so \
    vendor/ned/proprietarytoro/proprietary/libinvensense_mpl.so:system/vendor/lib/libinvensense_mpl.so \
    vendor/ned/proprietarytoro/proprietary/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/ned/proprietarytoro/proprietary/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/ned/proprietarytoro/proprietary/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/ned/proprietarytoro/proprietary/libsec-ril_lte.so:system/vendor/lib/libsec-ril_lte.so \
    vendor/ned/proprietarytoro/proprietary/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/ned/proprietarytoro/proprietary/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/ned/proprietarytoro/proprietary/libusc.so:system/vendor/lib/libusc.so

# All the apks necessary for toro
PRODUCT_PACKAGES += \
    BIP \
    IMSFramework \
    RTN \
    SDM \
    SPG \
    SyncMLSvc

# BIP

include $(CLEAR_VARS)

LOCAL_MODULE := BIP
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# IMSFramework

include $(CLEAR_VARS)

LOCAL_MODULE := IMSFramework
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# RTN

include $(CLEAR_VARS)

LOCAL_MODULE := RTN
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# SDM

include $(CLEAR_VARS)

LOCAL_MODULE := SDM
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# SPG

include $(CLEAR_VARS)

LOCAL_MODULE := SPG
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# SyncMLSvc

include $(CLEAR_VARS)

LOCAL_MODULE := SyncMLSvc
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

